const singleton = require('./singleton');
const factory = require('./factory');
const abstractFactory = require('./abstractFactory');
const prototype = require('./prototype');
const builder = require('./builder');
const decorator = require('./decorator');
const facade = require('./facade');
const proxy = require('./proxy');
const adapter = require('./adapter');
const composite = require('./composite');

singleton();
factory();
abstractFactory();
prototype();
builder();
decorator();
facade();
proxy();
adapter();
composite();
